# https://github.com/lowlighter/metrics
name: Metrics
on:
  schedule: 
    - cron: 0 */4 * * * # every 4 hours
  workflow_dispatch:
  push: 
    branches:
     - main
    paths:
     - .github/workflows/metrics*.yml
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Isometric Calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Rome
          base: ''
          # Options
          filename: ${{ vars.METRICS_DIR }}/isocalendar.svg
          plugin_isocalendar: yes

      - name: Languages (recent)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Rome
          base: ''
          # Options
          filename: ${{ vars.METRICS_DIR }}/recent-languages.svg
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: 'recently-used'
          plugin_languages_details: 'percentage, lines'

      - name: Languages (most used)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Rome
          base: ''
          # Options
          filename: ${{ vars.METRICS_DIR }}/most-used-languages.svg
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: 'most-used'
          plugin_languages_details: 'percentage, lines'

      - name: Leetcode
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Rome
          base: ''
          # Options
          filename: ${{ vars.METRICS_DIR }}/leetcode.svg
          plugin_leetcode: yes
          plugin_leetcode_sections: solved
