# https://github.com/lowlighter/metrics
name: Metrics
on:
  schedule: 
    - cron: "0 */12 * * *" # every 12 hours
  workflow_dispatch:
  push: 
    branches:
     - main
    paths:
     - '.github/workflows/metrics*.yml'
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 'Isometric Calendar'
        uses: lowlighter/metrics@latest
        with:
          filename: ${{ vars.METRICS_DIR }}/isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Rome
          base: ''
          # Options
          plugin_isocalendar: yes

      - name: 'Languages'
        uses: lowlighter/metrics@latest
        with:
          filename: ${{ vars.METRICS_DIR }}/languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Rome
          base: ''
          # Options
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: 'recently-used'
          plugin_languages_details: 'percentage, lines'
