# https://github.com/lowlighter/metrics
name: Metrics
on:
  schedule: 
    - cron: "0 */12 * * *" # every 12 hours
  workflow_dispatch:
  push: 
    branches:
     - main
    paths:
     - '.github/workflows/metrics*.yml'
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
        - uses: lowlighter/metrics@latest
          with:
            filename: github-metrics.svg
            token: ${{ secrets.METRICS_TOKEN }}
            config_timezone: Europe/Rome
            config_order: base, habits, isocalendar, languages
            # base
            base_indepth: yes
            base: header, activity, community
            # habits
            plugin_habits: yes
            plugin_habits_charts: yes
            plugin_habits_facts: no
            # isocalendar
            plugin_isocalendar: yes
            plugin_isocalendar_duration: half-year
            # languages
            plugin_languages: yes
            plugin_languages_indepth: yes
            plugin_languages_sections: most-used, recently-used
            plugin_languages_details: percentage, lines
            # # leetcode
            # plugin_leetcode: yes
            # plugin_leetcode_sections: solved, skills
